2022/DiceCTF/your-space/server/app/__init__.py
from pathlib import Path

from flask import Flask
from flask_caching import Cache
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from .notify import start_notifier

cache = Cache()
db = SQLAlchemy()
login = LoginManager()
login.login_view = "auth.login"
login.login_message = "not logged in"

flag_path = Path(__file__).parent / "flag.txt"
assert flag_path.is_file()
flag = flag_path.read_text().strip()


def create_app():
    app = Flask(__name__)

    if app.env == "production":
        app.config.from_object("app.config.ProdConfig")
        flag_path.unlink()
    else:
        app.config.from_object("app.config.DevConfig")

    cache.init_app(app)
    db.init_app(app)
    login.init_app(app)

    from .routes import auth, main, space

    app.register_blueprint(auth)
    app.register_blueprint(main)
    app.register_blueprint(space)

    with app.app_context():
        db.create_all()

    start_notifier()

    return app

2022/DiceCTF/your-space/server/app/routes/__init__.py
from .auth import auth
from .main import main
from .space import space

__all__ = ["auth", "main", "space"]

2022/DiceCTF/your-space/server/app/routes/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user

from .. import db
from ..form import LoginForm, RegisterForm
from ..model import User

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if user.check_password(form.password.data):
                login_user(user)
                flash("logged in")
                next_url = request.args.get("next")
                if next_url is not None and next_url.startswith("/"):
                    return redirect(next_url)
                return redirect(url_for("main.profile"))
        else:
            flash("invalid login")
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash("logged in")
        return redirect(url_for("main.profile"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    flash("logged out")
    return redirect(url_for("main.home"))

2022/DiceCTF/your-space/server/app/routes/main.py
from flask import Blueprint, flash, render_template
from flask_login import current_user, login_required

from .. import db
from ..form import WebhookForm
from ..model import Space

main = Blueprint("main", __name__)


@main.route("/")
def home():
    spaces = Space.query.all()
    return render_template("home.html", spaces=spaces)


@main.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = WebhookForm()
    if form.validate_on_submit():
        current_user.webhook = form.webhook.data
        db.session.add(current_user)
        db.session.commit()
        flash("webhook updated")
    return render_template("profile.html", form=form)

2022/DiceCTF/your-space/server/app/routes/space.py
from flask import Blueprint, abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from .. import cache, db
from ..form import PostForm, SpaceForm
from ..model import Post, Space, Subscription
from ..notify import notify

space = Blueprint("space", __name__)


def get_subscription(user, space):
    query = Subscription.query.filter_by(user=user).filter_by(space=space)
    return query.first()


@cache.memoize(timeout=60)
def num_subscriptions(space_id):
    return len(Subscription.query.filter_by(space_id=space_id).all())


@space.route("/space/<space_id>")
def view(space_id):
    space = Space.query.get(space_id)
    if space is None:
        return abort(404)
    subscribed = None
    if current_user.is_authenticated:
        subscribed = get_subscription(current_user, space) is not None
    subs = num_subscriptions(space.id)
    return render_template("space.html", subscribed=subscribed, subs=subs, space=space)


@space.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = SpaceForm()
    if form.validate_on_submit():
        space = Space(name=form.name.data, user=current_user)
        db.session.add(space)
        db.session.commit()
        flash("space created")
        return redirect(url_for("space.view", space_id=space.id))
    return render_template("create.html", form=form)


@space.route("/space/<space_id>/post", methods=["GET", "POST"])
@login_required
def post(space_id):
    space = Space.query.get(space_id)
    if space is None:
        return abort(404)
    if space.user_id != current_user.id:
        return abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post = Post(content=form.content.data, space=space)
        db.session.add(post)
        db.session.commit()
        notify(post)
        flash("post created")
        return redirect(url_for("space.view", space_id=space.id))
    return render_template("post.html", form=form, space=space)


@space.route("/space/<space_id>/sub")
@login_required
def sub(space_id):
    space = Space.query.get(space_id)
    if space is None:
        return abort(404)
    if get_subscription(current_user, space) is None:
        subscription = Subscription(user=current_user, space=space)
        db.session.add(subscription)
        db.session.commit()
        flash("subscribed")
    return redirect(url_for("space.view", space_id=space.id))


@space.route("/space/<space_id>/unsub")
@login_required
def unsub(space_id):
    space = Space.query.get(space_id)
    if space is None:
        return abort(404)
    subscription = get_subscription(current_user, space)
    if subscription is not None:
        db.session.delete(subscription)
        db.session.commit()
        flash("unsubscribed")
    return redirect(url_for("space.view", space_id=space.id))

2022/DiceCTF/your-space/server/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - your space</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  </head>
  <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="msg">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

2022/DiceCTF/your-space/server/app/templates/create.html
{% from "form.html" import render_field %}
{% extends "base.html" %}
{% block title %}create space{% endblock %}

{% block content %}
<h1>create space</h1>
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <a href="{{ url_for('main.profile') }}">profile</a>
</nav>
<hr>
<form method="POST">
  {{ render_field(form.name) }}
  {{ form.submit }}
</form>
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/form.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs) }}
  {% if field.errors %}
  <p class="error">
    {% for error in field.errors %}
    {{ error }} <br>
    {% endfor %}
  </p>
  {% endif %}
</div>
{% endmacro %}

2022/DiceCTF/your-space/server/app/templates/home.html
{% extends "base.html" %}
{% block title %}home{% endblock %}

{% block content %}
<h1>your space</h1>
<nav>
  {% if current_user.is_authenticated %}
  <a href="{{ url_for('main.profile') }}">profile</a>
  <a href="{{ url_for('auth.logout') }}">logout</a>
  {% else %}
  <a href="{{ url_for('auth.login') }}">login</a>
  <a href="{{ url_for('auth.register') }}">register</a>
  {% endif %}
</nav>
<hr>
<h2>spaces</h2>
{% if spaces %}
<ul>
  {% for space in spaces %}
  <li><a href="{{ url_for('space.view', space_id=space.id) }}">{{ space.user.username }}: {{ space.name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>there are no spaces yet</p>
{% endif %}
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/login.html
{% from "form.html" import render_field %}
{% extends "base.html" %}
{% block title %}login{% endblock %}

{% block content %}
<h1>login</h1>
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <a href="{{ url_for('auth.register') }}">register</a>
</nav>
<hr>
<form method="POST">
  {{ render_field(form.username) }}
  {{ render_field(form.password) }}
  {{ form.submit }}
</form>
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/post.html
{% from "form.html" import render_field %}
{% extends "base.html" %}
{% block title %}post{% endblock %}

{% block content %}
<h1>post</h1>
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <a href="{{ url_for('main.profile') }}">profile</a>
</nav>
<hr>
<h2>post to {{ space.name }}</h2>
<form method="POST">
  {{ render_field(form.content) }}
  {{ form.submit }}
</form>
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/profile.html
{% from "form.html" import render_field %}
{% extends "base.html" %}
{% block title %}profile{% endblock %}

{% block content %}
<h1>{{ current_user.username }}</h1>
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <a href="{{ url_for('space.create') }}">create space</a>
</nav>
<hr>
<h2>update notification webhook</h2>
<form method="POST">
  {{ render_field(form.webhook, value=current_user.webhook) }}
  {{ form.submit }}
</form>
<hr>
<h2>subscriptions</h2>
{% if current_user.subscriptions %}
<ul>
  {% for sub in current_user.subscriptions %}
  <li><a href="{{ url_for('space.view', space_id=sub.space.id) }}">{{ sub.space.name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>you have no subscriptions</p>
{% endif %}
<hr>
<h2>spaces</h2>
{% if current_user.spaces %}
<ul>
  {% for space in current_user.spaces %}
  <li><a href="{{ url_for('space.view', space_id=space.id) }}">{{ space.name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>you have no spaces</p>
{% endif %}
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/register.html
{% from "form.html" import render_field %}
{% extends "base.html" %}
{% block title %}register{% endblock %}

{% block content %}
<h1>register</h1>
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <a href="{{ url_for('auth.login') }}">login</a>
</nav>
<hr>
<form method="POST">
  {{ render_field(form.username) }}
  {{ render_field(form.password) }}
  {{ form.submit }}
</form>
{% endblock %}

2022/DiceCTF/your-space/server/app/templates/space.html
{% extends "base.html" %}
{% block title %}{{ space.name }}{% endblock %}

{% block content %}
<h1>{{ space.name }}</h1>
<h2>by {{ space.user.username }}</h2>
{{ subs }} subscriber{{ 's' if subs != 1 }}
<nav>
  <a href="{{ url_for('main.home') }}">home</a>
  <br>
  {% if current_user.is_authenticated and subscribed %}
  <a href="{{ url_for('space.unsub', space_id=space.id) }}">unsubscribe</a>
  {% else %}
  <a href="{{ url_for('space.sub', space_id=space.id) }}">subscribe</a>
  {% endif %}
  {% if current_user.is_authenticated and current_user.id == space.user_id %}
  <br>
  <a href="{{ url_for('space.post', space_id=space.id) }}">post to this space</a>
  {% endif %}
</nav>
{% if space.posts %}
{% for post in space.posts|sort(attribute='timestamp', reverse=True) %}
<hr>
<p>{{ post.content }}</p>
<p class="timestamp">{{ post.timestamp }}</p>
{% endfor %}
{% else %}
<hr>
<p>there are no posts yet...</p>
{% endif %}
{% endblock %}